package icon
// This file is auto generated
// Using Lucide icons version 0.525.0
var Activity = Icon("activity")
var Building2 = Icon("building-2")
var Check = Icon("check")
var CreditCard = Icon("credit-card")
var DollarSign = Icon("dollar-sign")
var Ellipsis = Icon("ellipsis")
var ExternalLink = Icon("external-link")
var FileText = Icon("file-text")
var FolderGit2 = Icon("folder-git-2")
var Github = Icon("github")
var House = Icon("house")
var Info = Icon("info")
var LayoutDashboard = Icon("layout-dashboard")
var Lock = Icon("lock")
var LogOut = Icon("log-out")
var Mail = Icon("mail")
var Notebook = Icon("notebook")
var PanelLeftOpen = Icon("panel-left-open")
var Pencil = Icon("pencil")
var Phone = Icon("phone")
var Plus = Icon("plus")
var Rss = Icon("rss")
var Search = Icon("search")
var Trash2 = Icon("trash-2")
var TrendingDown = Icon("trending-down")
var TrendingUp = Icon("trending-up")
var TriangleAlert = Icon("triangle-alert")
var Upload = Icon("upload")
var Users = Icon("users")
var X = Icon("x")
