// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func mdNotes(notes string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(markdownToTailwindHTML(notes)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// markdownToTailwindHTML renders markdown to HTML with Tailwind classes using goldmark
func markdownToTailwindHTML(md string) string {
	var buf bytes.Buffer
	mdParser := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
	)
	if err := mdParser.Convert([]byte(md), &buf); err != nil {
		return md
	}
	html := buf.String()
	// Apply Tailwind classes to common markdown elements
	html = strings.ReplaceAll(html, "<h1>", "<h1 class=\"text-2xl font-bold mt-4 mb-2\">")
	html = strings.ReplaceAll(html, "<h2>", "<h2 class=\"text-xl font-semibold mt-3 mb-2\">")
	html = strings.ReplaceAll(html, "<h3>", "<h3 class=\"text-lg font-medium mt-2 mb-1\">")
	html = strings.ReplaceAll(html, "<ul>", "<ul class=\"list-disc pl-6 my-2\">")
	html = strings.ReplaceAll(html, "<ol>", "<ol class=\"list-decimal pl-6 my-2\">")
	html = strings.ReplaceAll(html, "<li>", "<li class=\"mb-1\">")
	html = strings.ReplaceAll(html, "<p>", "<p class=\"mb-2\">")
	html = strings.ReplaceAll(html, "<a ", "<a class=\"text-muted-foreground hover:text-primary underline\" ")
	html = strings.ReplaceAll(html, "<pre>", "<pre class=\"bg-muted rounded p-2 my-2 overflow-x-auto text-sm\">")
	html = strings.ReplaceAll(html, "<code>", "<code class=\"bg-muted px-1 rounded text-sm\">")
	html = strings.ReplaceAll(html, "<blockquote>", "<blockquote class=\"border-l-4 border-muted-foreground pl-4 italic my-2 text-muted-foreground\">")
	html = strings.ReplaceAll(html, "<table>", "<table class=\"table-auto min-w-full my-4\">")
	html = strings.ReplaceAll(html, "<th>", "<th class=\"border border-muted p-2 bg-muted font-semibold text-left\">")
	html = strings.ReplaceAll(html, "<td>", "<td class=\"border border-muted p-2\">")
	return html
}

var _ = templruntime.GeneratedTemplate
